In [66]:
# Class exercise: table
import numpy as np

a = np.arange(10, 30).reshape(4, 5)

yellow = a[0,0]
light_blue = a[:,1::2]
red = a[0,1:4]
green = a[0:3,2]
blue = a[0::2,-1]

print('yellow:',yellow, '\nlight_blue', light_blue, '\nred', red, '\ngreen', green, '\nblue', blue)

yellow: 10 
light_blue [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
red [11 12 13] 
green [12 17 22] 
blue [14 24]


In [69]:
#Class exercise: cube
import numpy as np

a = np.arange(0, 27).reshape((3, 3, 3))

print("1:", a[1,1,:])
print("2:", a[:,1,0])
print("3:", a[0,:,2])

1: [12 13 14]
2: [ 3 12 21]
3: [2 5 8]


In [106]:
#Class exercise: masking
import numpy as np

data = np.arange(1,101).reshape(10,10)
print('1:',data[(data%2 == 0)])
print('2',data[np.where(data%10==6)])
print('3',data[np.where((data%10==8) | (data%3==0))])

1: [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
2 [ 6 16 26 36 46 56 66 76 86 96]
3 [ 3  6  8  9 12 15 18 21 24 27 28 30 33 36 38 39 42 45 48 51 54 57 58 60
 63 66 68 69 72 75 78 81 84 87 88 90 93 96 98 99]


In [36]:
#Exercise numpy and csv
import numpy as np

filename = './befkbhalderstatkode.csv'

dd = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
print('1: ',dd)


mask_year_2015 = dd[:,0] == 2015
mask_german = dd[:,3] == 5180
mask_age = dd[:,2] == 0
print('2: ', np.sum(dd[(mask_year_2015) & (mask_german) & (mask_age)][:,4]))

def any_combination(AAR=None,BYDEL=None,ALDER=None,STATKODE=None): 
    if (AAR != None):
        mask_aar = dd[:,0] == AAR
    else:
        mask_aar = True
    if (BYDEL != None):
        mask_bydel = dd[:,1] == BYDEL
    else:
        mask_bydel = True
    if (ALDER != None):
        mask_alder = dd[:,2] == ALDER
    else:
        mask_alder = True
    if (ALDER != None): 
        mask_statcode = dd[:,3] == STATKODE
    else:
        mask_statcode = True
    return np.sum(dd[(mask_aar) & (mask_bydel) & (mask_alder) & (mask_statcode)][:,4])
print('3: ', any_combination(2015,None,0,5180))

def all_ages():
    

1:  [[2015    1    0 5100  614]
 [2015    1    0 5104    2]
 [2015    1    0 5106    1]
 ...
 [1992   99   89 5100    1]
 [1992   99   90 5180    1]
 [1992   99   93 5100    1]]
2:  35
3:  35
